### ISSUE TITLE
Proiect gol 🤔

### ISSUE THREAD

**Issue by Mufafa98** [Iuli21/bubble_buster#1]
![image](https://github.com/user-attachments/assets/74f8c398-c75c-462d-8296-1c32245e00d9)

**Comment by Iuli21** [comment]
Va trebui sa il fac privat si o sa pun comituri, daca pun acum toti vor avea asa proiectul

**Comment by Mufafa98** [comment]
Eu zic ca asta e motiv de depunctare.. zic sa rezolvi 🫢
